# Configuration of the api server

server:
    hostname: 127.0.0.1
    port: 8000

jwt:
    secret_key*: ${PSJWT_SECRET_KEY?mysecret}
    algorithm*: ${PSJWT_ALGORITHM}
    expires: 30

password:
    algorithm*: ${PSPASSWORD_ALGORITHM}
    encoding: "utf-8"
