# Configuration of the 3 parts of the application
# - API : access to data of the application from API Rest
# - WEB : retrieves HTML pages of the application
# - WebSocket : services handles by web socket between the client and the server  

api: interface/api.yml
web: interface/web.yml
websocket: interface/websocket.yml
