version: 1
verbose: True

reload:
    interval: 60

cleanup:
    interval: 86400
    directory: ${SYNCYTIUM_LOG_DIRECTORY}
    pattern: "^${APPLICATION}-.*\\.log$"
    nbdays: 20

formatters:
    standard:
        format: "%(asctime)s [%(levelname)-5s] (%(process)d:%(processName)s) %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ${SYNCYTIUM_LOG_DIRECTORY}/${APPLICATION}-${date:%Y-%m-%d}.log
        maxBytes: 16777216 # 16Mb
        backupCount: 10
        encoding: utf8

    server:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ${SYNCYTIUM_LOG_DIRECTORY}/fastapi-${date:%Y-%m-%d}.log
        maxBytes: 16777216 # 16Mb
        backupCount: 10
        encoding: utf8

loggers:
    fastapi:
        level: DEBUG
        handlers: [console, file, server]
        propagate: no

    uvicorn:
        level: INFO
        handlers: [console, file, server]
        propagate: no

    uvicorn.access:
        level: INFO
        handlers: [console, file, server]
        propagate: no

root:
    level: NOTSET
    handlers: [console, file]
