# Application log configuration

version: 1
verbose: True

syncytium:
    reload-disable:
        # time laps between 2 checks of evolution configuration (if {date} appears into an item)
        interval: 60

    cleanup-disable:
        # time laps between 2 checks of cleaning up log directory (remove older file)
        interval: 86400
        directory: ${PSLOG_DIRECTORY}
        pattern: "^${PROJECT}-.*\\.log$"
        nbdays: 20

    loggers:
        # list of logging loggers to redirect to DSLogger
        - fastapi
        - uvicorn

# Logging configuration

formatters:
    standard:
        format: "%(asctime)s [%(levelname)-5s] (%(process)d:%(processName)s) %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ${PSLOG_DIRECTORY}/${PROJECT}-${date:%Y-%m-%d}.log
        maxBytes: 16777216 # 16Mb
        backupCount: 10
        encoding: utf8

root:
    level: NOTSET
    handlers: [console, file]
