# Database configuration for the application
# TODO : These items must be secret ...
# TODO : Build APP_DATABASE_USERNAME and APP_DATABASE_PASSWORD

class: MySQL

parameters:
  hostname: "localhost"
  username: ${APP_DATABASE_USERNAME}
  password*: ${APP_DATABASE_PASSWORD}
  schema: "Syncytium"
