# Database configuration for the application
# TODO : These items must be secret ...

class: DSDatabaseMySQL

parameters:
  hostname: "localhost"
  username: "${ROOT_DATABASE_USERNAME}"
  password*: ${ROOT_DATABASE_PASSWORD}
  schema: "Syncytium"
